name: Terraform 

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs: 
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate 

      - name: Plan Terraform
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve tfplan

      - name: Terraform destroy 
        run: terraform destroy -auto-approve
